services:
  turtletrack:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: turtletrack
    restart: unless-stopped
    ports:
      - "8550:80"
    environment:
      - NODE_ENV=production
